CREATE DATABASE spotify;

CREATE USER auma WITH PASSWORD 'telesoftasTask';

GRANT ALL PRIVILEGES ON DATABASE spotify TO auma;

CREATE SCHEMA views AUTHORIZATION auma;

CREATE SCHEMA music AUTHORIZATION auma;